import {
  HuaweiMate50Pro,
  HuaweiMate50Pro1,
  HuaweiMate50Pro2,
  HuaweiNova11Pro,
  HuaweiNova11Pro1,
  HuaweiNova11Pro2,
  HuaweiP60Pro,
  HuaweiP60Pro1,
  HuaweiP60Pro2,
  iPhone15ProMax,
  iPhone15ProMax1,
  iPhone15ProMax2,
  iPhone14Plus,
  iPhone14Plus1,
  iPhone14Plus2,
  OnePlus10T,
  OnePlus10T1,
  OnePlus10T2,
  OnePlus11,
  OnePlus111,
  OnePlus112,
  OnePlus12,
  OnePlus121,
  OnePlus122,
  OppoFindX5,
  OppoFindX51,
  OppoFindX52,
  OppoReno10,
  OppoReno101,
  OppoReno102,
  SamsungGalaxyS22,
  SamsungGalaxyS221,
  SamsungGalaxyS222,
  SamsungGalaxyS23Plus,
  SamsungGalaxyS23Plus1,
  SamsungGalaxyS23Plus2,
  SamsungGalaxyS24Ultra,
  SamsungGalaxyS24Ultra1,
  SamsungGalaxyS24Ultra2,
  Xiaomi12,
  Xiaomi121,
  Xiaomi122,
  Xiaomi13T,
  Xiaomi13T1,
  Xiaomi13T2,
  XiaomiPoco,
  XiaomiPoco1,
  XiaomiPoco2,
} from "../assets"

export const smartPhones = [
  {
    id: 1,
    brand: "Apple",
    model: "iPhone 15 Pro Max",
    img: iPhone15ProMax2,
    memoryCapacity: 256,
    price: 1199,
    display: 6.7,
    ram: 6,
    chip: "Apple A17 Pro",
    otherImgs: [iPhone15ProMax, iPhone15ProMax1],
    operatingSystem: "iOS 17",
    cameraMain: "48MP + 12MP + 12MP Main",
    cameraFront: "12MP Front",
    rating: 5,
    ratingLeft: 0,
    quantity: 1,
  },
  {
    id: 2,
    brand: "Apple",
    model: "iPhone 14 Plus",
    img: iPhone14Plus2,
    memoryCapacity: 128,
    price: 699,
    display: 6.1,
    ram: 6,
    chip: "Apple A15 Bionic",
    otherImgs: [iPhone14Plus, iPhone14Plus1],
    operatingSystem: "iOS 16",
    cameraMain: "12MP + 12MP Main",
    cameraFront: "12MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 3,
    brand: "Huawei",
    model: "Mate 50 Pro",
    img: HuaweiMate50Pro2,
    memoryCapacity: 256,
    price: 874,
    display: 6.74,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8+ Gen 1",
    otherImgs: [HuaweiMate50Pro, HuaweiMate50Pro1],
    operatingSystem: "EMUI 13",
    cameraMain: " 50MP + 13MP + 64MP Main",
    cameraFront: "13MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 4,
    brand: "Huawei",
    model: "Nova 11 Pro",
    img: HuaweiNova11Pro2,
    memoryCapacity: 256,
    price: 799,
    display: 6.78,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 778G",
    otherImgs: [HuaweiNova11Pro, HuaweiNova11Pro1],
    operatingSystem: "EMUI 13",
    cameraMain: " 50MP + 8MP Main, 60MP",
    cameraFront: "8MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 5,
    brand: "Huawei",
    model: "P60 Pro",
    img: HuaweiP60Pro2,
    memoryCapacity: 256,
    price: 1123,
    display: 6.67,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8+ Gen 1 ",
    otherImgs: [HuaweiP60Pro, HuaweiP60Pro1],
    operatingSystem: "EMUI 13.1",
    cameraMain: " 48MP + 13MP + 48MP Main",
    cameraFront: "13MP Front",
    rating: 5,
    ratingLeft: 0,
    quantity: 1,
  },
  {
    id: 6,
    brand: "OnePlus",
    model: "10T",
    img: OnePlus10T2,
    memoryCapacity: 128,
    price: 949,
    display: 6.7,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8+ Gen 1 ",
    otherImgs: [OnePlus10T, OnePlus10T1],
    operatingSystem: "Android 12",
    cameraMain: " 50MP + 8MP + 2MP Main",
    cameraFront: "16MP Front",
    rating: 3,
    ratingLeft: 2,
    quantity: 1,
  },
  {
    id: 7,
    brand: "OnePlus",
    model: "11",
    img: OnePlus112,
    memoryCapacity: 128,
    price: 899,
    display: 6.7,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8 Gen 2",
    otherImgs: [OnePlus11, OnePlus111],
    operatingSystem: "Android 13",
    cameraMain: "50MP + 32MP + 48MP Main",
    cameraFront: "16MP Front ",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 8,
    brand: "OnePlus",
    model: "12",
    img: OnePlus122,
    memoryCapacity: 256,
    price: 1120,
    display: 6.82,
    ram: 12,
    chip: "Qualcomm Snapdragon™ 8 Gen 3",
    otherImgs: [OnePlus12, OnePlus121],
    operatingSystem: "Android 14",
    cameraMain: " 50MP + 48MP + 64MP Main",
    cameraFront: "32MP Front ",
    rating: 5,
    ratingLeft: 0,
    quantity: 1,
  },
  {
    id: 9,
    brand: "OPPO",
    model: "Find X5 Pro",
    img: OppoFindX52,
    memoryCapacity: 256,
    price: 998,
    display: 6.7,
    ram: 12,
    chip: "Qualcomm Snapdragon™ 8+ Gen 1",
    otherImgs: [OppoFindX5, OppoFindX51],
    operatingSystem: "Android 12",
    cameraMain: " 50MP + 50MP + 13MP Main",
    cameraFront: "32MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 10,
    brand: "OPPO",
    model: "Reno 10 Pro",
    img: OppoReno102,
    memoryCapacity: 256,
    price: 574,
    display: 6.7,
    ram: 12,
    chip: "Qualcomm Snapdragon™ 778G",
    otherImgs: [OppoReno10, OppoReno101],
    operatingSystem: "Android 13",
    cameraMain: " 50MP + 32MP + 8MP Main",
    cameraFront: "32MP Front",
    rating: 3,
    ratingLeft: 2,
    quantity: 1,
  },
  {
    id: 11,
    brand: "Samsung",
    model: "Galaxy S22",
    img: SamsungGalaxyS222,
    memoryCapacity: 128,
    price: 999,
    display: 6.1,
    ram: 8,
    chip: "Samsung Exynos 2200",
    otherImgs: [SamsungGalaxyS22, SamsungGalaxyS221],
    operatingSystem: "Android 12",
    cameraMain: " 50MP + 12MP + 10MP Main",
    cameraFront: "10MP Front",
    rating: 3,
    ratingLeft: 2,
    quantity: 1,
  },
  {
    id: 12,
    brand: "Samsung",
    model: "Galaxy S23 Plus",
    img: SamsungGalaxyS23Plus2,
    memoryCapacity: 256,
    price: 1249,
    display: 6.6,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8 Gen 2",
    otherImgs: [SamsungGalaxyS23Plus, SamsungGalaxyS23Plus1],
    operatingSystem: "Android 13",
    cameraMain: " 50MP + 10MP + 12MP Main",
    cameraFront: "12MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
  {
    id: 13,
    brand: "Samsung",
    model: "Galaxy S24 Ultra",
    img: SamsungGalaxyS24Ultra2,
    memoryCapacity: 256,
    price: 1648,
    display: 6.8,
    ram: 12,
    chip: "Qualcomm Snapdragon™ 8 Gen 3",
    otherImgs: [SamsungGalaxyS24Ultra, SamsungGalaxyS24Ultra1],
    operatingSystem: "Android 14",
    cameraMain: " 200MP + 12MP + 10MP + 50MP Main",
    cameraFront: "12MP Front",
    rating: 5,
    ratingLeft: 0,
    quantity: 1,
  },
  {
    id: 14,
    brand: "Xiaomi",
    model: "13T Pro",
    img: Xiaomi13T2,
    memoryCapacity: 512,
    price: 999,
    display: 6.67,
    ram: 12,
    chip: "MediaTek Dimensity 9200+",
    otherImgs: [Xiaomi13T, Xiaomi13T1],
    operatingSystem: "HyperOS",
    cameraMain: "50MP + 50MP + 12MP Main",
    cameraFront: "20MP Front",
    rating: 5,
    ratingLeft: 0,
    quantity: 1,
  },
  {
    id: 15,
    brand: "Xiaomi",
    model: "12",
    img: Xiaomi122,
    memoryCapacity: 128,
    price: 599,
    display: 6.28,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 870",
    otherImgs: [Xiaomi12, Xiaomi121],
    operatingSystem: "MIUI 14",
    cameraMain: " 50MP + 13MP + 5MP Main",
    cameraFront: "32MP Front",
    rating: 3,
    ratingLeft: 2,
    quantity: 1,
  },
  {
    id: 16,
    brand: "Xiaomi",
    model: "Poco F4 GT",
    img: XiaomiPoco2,
    memoryCapacity: 128,
    price: 689,
    display: 6.67,
    ram: 8,
    chip: "Qualcomm Snapdragon™ 8+ Gen 1",
    otherImgs: [XiaomiPoco, XiaomiPoco1],
    operatingSystem: "MIUI 12",
    cameraMain: " 64MP + 8MP + 2MP Main",
    cameraFront: "20MP Front",
    rating: 4,
    ratingLeft: 1,
    quantity: 1,
  },
]
